source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def standard_pods
    pod 'SwiftyXMLParser'
    pod 'CryptoSwift'
end

target 'YouSign' do
	standard_pods
end

target 'YouSignTestTarget' do
	standard_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.1'
        end
    end
end
